# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macid1', models.CharField(default=0, max_length=50)),
                ('macid2', models.CharField(default=0, max_length=50)),
                ('macid3', models.CharField(default=0, max_length=50)),
                ('maccount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('productimage', models.ImageField(upload_to='productimages')),
                ('link', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companylogo', models.ImageField(upload_to='companylogos')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcheck', models.CharField(default=0, max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchases',
            name='curruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.UserProfile'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='softwareinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Softwares'),
        ),
    ]
